package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Activator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-linux-amd64/jdk8u73/6086/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Friday, January 29, 2016 5:40:37 PM PST
*/

public interface Activator extends ActivatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Activator
